/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LabValue = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Float64 });
export const Patient = IDL.Record({
  'id' : IDL.Text,
  'age' : IDL.Nat,
  'sex' : IDL.Text,
  'clinicalHistory' : IDL.Text,
  'labValues' : IDL.Vec(LabValue),
  'name' : IDL.Text,
});
export const Differential = IDL.Record({
  'probability' : IDL.Float64,
  'condition' : IDL.Text,
});
export const DiagnosisResult = IDL.Record({
  'differentials' : IDL.Vec(Differential),
  'confidence' : IDL.Float64,
  'condition' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPatient' : IDL.Func([Patient], [], []),
  'analyzePatient' : IDL.Func([Patient], [DiagnosisResult], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LabValue = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Float64 });
  const Patient = IDL.Record({
    'id' : IDL.Text,
    'age' : IDL.Nat,
    'sex' : IDL.Text,
    'clinicalHistory' : IDL.Text,
    'labValues' : IDL.Vec(LabValue),
    'name' : IDL.Text,
  });
  const Differential = IDL.Record({
    'probability' : IDL.Float64,
    'condition' : IDL.Text,
  });
  const DiagnosisResult = IDL.Record({
    'differentials' : IDL.Vec(Differential),
    'confidence' : IDL.Float64,
    'condition' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPatient' : IDL.Func([Patient], [], []),
    'analyzePatient' : IDL.Func([Patient], [DiagnosisResult], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };