/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DiagnosisResult {
  'differentials' : Array<Differential>,
  'confidence' : number,
  'condition' : string,
}
export interface Differential { 'probability' : number, 'condition' : string }
export interface LabValue { 'key' : string, 'value' : number }
export interface Patient {
  'id' : string,
  'age' : bigint,
  'sex' : string,
  'clinicalHistory' : string,
  'labValues' : Array<LabValue>,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPatient' : ActorMethod<[Patient], undefined>,
  'analyzePatient' : ActorMethod<[Patient], DiagnosisResult>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];